- name: install Mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes
  
- name: set up root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1